### ISSUE TITLE
R version pin issue

### ISSUE THREAD

**Issue by GeorgianaElena** [utoronto-2i2c/jupyterhub-deploy#110]
### Originally reported in: https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/107#issue-1005066505 by @yuvipanda 

*The version of RStudio we were deploying is too old for
R 4.1's graphics engine, causing this error:*

> R graphics engine version 14 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed.`

*So we pin R to 4.0 until we can resolve that. The underlying
issue is tracked in https://github.com/jupyterhub/jupyter-rsession-proxy/issues/97*

### Solution
We tried to address this in the following PRs:
- https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/107
- https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/109
- https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/108

### Problem
I can still see the R, RStudio version incompatibility warning and the newer R version :eyes: 
![r-version-stagng](https://user-images.githubusercontent.com/7579677/134673807-a0ef3b91-b205-4270-9417-1f106d49710f.png)

**Comment by yuvipanda** [comment]
It's back to R 4.1. I think this is why I removed r-recommended in the berkeley image - it might be coming from a different apt repository. Can you try interactively doing this without that package?

**Comment by yuvipanda** [comment]
I tried this #111, but did not work - with `E: Unable to correct problems, you have held broken packages.`

**Comment by yuvipanda** [comment]
It's failing with:

```
Step 21/47 : RUN apt-get update -qq --yes > /dev/null &&     apt-get install --yes -qq     r-base=${R_VERSION}     r-base-dev=${R_VERSION}     r-cran-littler=0.3.11-1.2004.0     nodejs     npm > /dev/null
 ---> Running in 18b2b7e45878
E: Unable to correct problems, you have held broken packages.
```

So I'm going to debug this by deleting all lines in the Dockerfile from that line, so the image itself builds up until that point. Then I can do a `docker run` into it, and then try things manually to iterate

**Comment by yuvipanda** [comment]
https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/112 is the result, the PR there has more description of the process I undertook

**Comment by choldgraf** [comment]
Is #112 deployed to the staging hub? I am still seeing R v4.1 on there.

**Comment by choldgraf** [comment]
this is now deployed in production as well (https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/113), so I'm going to close this :-)

thanks @GeorgianaElena and @yuvipanda for iterating so much to figure this one out!
