### ISSUE TITLE
R  System Lib suggestions

### ISSUE THREAD

**Issue by ntaback** [utoronto-2i2c/jupyterhub-deploy#25]
I took my local system library and tried to curate a list.  Anyway, this should be a reasonable start.

"airports"
"brew"
"broom"
"BsMD"
"combinat"
"curl"
"dbplyr"
"devtools"
"DoE.base"
"dplyr"
"DT"
"emmeans"
"fivethirtyeight"
"forcats"
"foreign"
"FrF2"
"ggdendro"
"ggforce"
"ggplot2"
"gmodels"
"googledrive"
"googlesheets4"
"gridExtra"
"gtable"
"gtools"
"gutenbergr"
"htmltools"
"htmlwidgets"
"httpuv"
"httr"
"janeaustenr"
"janitor"
"jpeg"
"jsonlite"
"kableExtra"
"KernSmooth"
"knitr"
"labeling"
"lattice"
"latticeExtra"
"lazyeval"
"leaflet"
"leaflet.providers"
"learnr"
"lme4"
"lubridate"
"magrittr"
"markdown"
"MASS"
"Matching"
"Matrix"
"mgcv"
"mime"
"miniUI"
"mosaic"
"mosaicCore"
"mosaicData"
"multcomp"
"mvtnorm"
"nlme"
"nnet"
"nycflights13"
"openintro"
"openssl"
"parallel"
"partitions"
"pillar"
"pkgbuild"
"pkgconfig"
"pkgload"
"plotROC"
"plyr"
"png"
"polyclip"
"polynom"
"praise"
"prettydoc"
"prettyunits"
"processx"
"progress"
"promises"
"proto"
"ps"
"purrr"
"pwr"
"RColorBrewer"
"Rcpp"
"RcppArmadillo"
"RcppEigen"
"readr"
"readxl"
"rematch"
"rematch2"
"remotes"
"renv"
"reprex"
"reshape2"
"reticulate"
"rex"
"rlang"
"rmarkdown"
"roxygen2"
"rpart"
"rprojroot"
"RSelenium"
"rtweet"
"rvest"
"sandwich"
"scales"
"scatterplot3d"
"scholar"
"selectr"
"semver"
"servr"
"sessioninfo"
"sets"
"sfsmisc"
"shiny"
"showtext"
"showtextdb"
"snakecase"
"SnowballC"
"sourcetools"
"sp"
"spatial"
"splines"
"statmod"
"stats"
"stats4"
"stopwords"
"stringi"
"stringr"
"survival"
"sys"
"sysfonts"
"tcltk"
"testthat"
"TH.data"
"tibble"
"tidygraph"
"tidyr"
"tidyselect"
"tidytext"
"tidyverse"
"tinytex"
"tokenizers"
"tools"
"urltools"
"usdata"
"usethis"
"utf8"
"xaringan"
"xfun"
"XML"
"xml2"
"xopen"
"xtable"
"yaml"

**Comment by yuvipanda** [comment]
I wanna get this validated before start of semester :) 

How to make this happen:

1. Login to jupyter.utoronto.edu, and in R run `installed.packages()`
2. Find things in this list that aren't in that list
3. Find latest version of them from https://packagemanager.rstudio.com/client/#/repos/1/packages
4. Add an entry to deployments/utoronto/image/install.R

This should also help us test the newly-fixed continuous deployment workflow (see #45)
