### ISSUE TITLE
Install nbgrader

### ISSUE THREAD

**Issue by ntaback** [utoronto-2i2c/jupyterhub-deploy#27]

**Comment by yuvipanda** [comment]
nbgrader makes some very specific assumptions about the shape of the hub it runs on - around user ids, home directory structure, permissions, etc. They don't map very well to the distributed scalable cloud hubs, so it isn't easy to use it as one would use nbgrader, unfortunately.

**Comment by ntaback** [comment]
thanks @yuvipanda.  Could https://ds-modules.github.io/curriculum-guide/workflow/collecting-grading-assignments.html be implemented for Jupyter nbs?  https://rstudio.github.io/learnr/ could be implemented for RStudio.  In both cases it would be great to have a workflow where instructors can autograde then grades are exported into our LMS (Canvas).
