### ISSUE TITLE
Launch from a binder?

### ISSUE THREAD

**Issue by jobovy** [utoronto-2i2c/jupyterhub-deploy#29]
Hi,

I'm looking to use this JupyterHub for my graduate class this year (see [jobovy/AST1420](https://github.com/jobovy/AST1420)) and I'd like to set up an environment for [this binder](https://github.com/jobovy/galastro-binder), which has all of the pre-requisites for my class. However, when I use [nbgitpuller](https://jupyterhub.github.io/nbgitpuller/link) to create a binder link (using the binder tab), I'm getting a [link](https://utoronto.2i2c.cloud/v2/gh/jobovy/galastro-binder/master?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fjobovy%252Fgalastro-binder%26urlpath%3Dtree%252Fgalastro-binder%252F%26branch%3Dmaster) that doesn't work (the URL seems very specific to binder and gives a 404). If I use the JupyterHub tab instead, I get a server, but it doesn't install the pre-requisites. 

Is using a binder to specify the course's pre-requisites supposed to work? I should note that I'm also unable to get a working jupyter notebook just using binder itself as the hub, for reasons that I don't understand.

**Comment by ntaback** [comment]
@yuvipanda could you install the packages in https://github.com/jobovy/galastro-binder/blob/master/environment.yml ?  Otherwise, the packages could be installed by the students.

**Comment by jobovy** [comment]
@ntaback --Thanks for looking into this! Seems like using a binder to set up the environment doesn't work then? There's no need to install the packages centrally, because they may need to be updated regularly and I've figured out how to install everything in just a few shell commands. It might be useful to install the GSL (GNU Scientific Library) centrally; this is installed on syzygy, so it makes the installation of the other packages a little easier. But it's also easy enough to do it in a notebook with
```
!conda install -y -c conda-forge gsl
```

**Comment by yuvipanda** [comment]
Hey @jobovy! I've installed astropy, astroquery and galpy centrally (see https://github.com/utoronto-2i2c/jupyterhub-deploy/commit/52e5675647bf63d9757772424e2b966284e49fc3). Unfortunately, it can't launch from arbitrary binder repositories - nbgitpuller only pulls in content, not environments.

**Comment by jobovy** [comment]
Okay, great, thanks @yuvipanda!
