### ISSUE TITLE
Package requests

### ISSUE THREAD

**Issue by elb0** [utoronto-2i2c/jupyterhub-deploy#31]
Hi Yuvi,

The Department of Statistical Sciences is running an event where students make 'aRt' (art with R). It would make things way smoother to have the packages below already available as some require some extra steps (dialogue prompts in the console), but they are also packages that won't be used that often outside this event. 

Would it be okay to add them as part of `install.R` or will that make things too clunky on the backend and we should just plan to talk students through the process?

Thanks!
Liza

```
install.packages("ggforce") # an extension to ggplot - used in circles example
install.packages("ggthemes")
install.packages("devtools") 
devtools::install_github("cutterkom/generativeart") # generativeart package also used in some examples
devtools::install_github("djnavarro/flametree")
```

**Comment by ntaback** [comment]
@elb0 cool that you plan to use this for aRt!! . `devtools` is already installed in base.  @yuvipanda: I'm not sure if you want to install non-CRAN packages into base?  @elb0 try installing the packages to be sure that they work.

**Comment by yuvipanda** [comment]
This is very awesome! I'm happy to install packages from github on the base image too. However, for both CRAN packages & from GitHub, I think we should explicitly specify versions. I usually find CRAN package versions from https://packagemanager.rstudio.com/client/#/repos/1/packages, while the GitHub repos usually have a tagged version. The goal is for us to be able to rebuild the image without accidentally upgrading something.

Would you be willing to make a pull request to install.R, @elb0? If not, I'll do it tomorrow (still stuck in India, unfortunately).

Thanks!

**Comment by elb0** [comment]
Thanks so much @yuvipanda and @ntaback! 

Yuvi, anytime before Friday is awesome so I'll just leave that with you if that is okay. I'll be a proper pull-er next time I wanna bug you ;) 

- The `ggforce` and `ggthemes` versions shown on packagemanger are perfect (0.3.2 and 4.2.0 respectively)
- For `flametree` version 0.0.0.9000
- For `generativeart` version 1.0

**Comment by yuvipanda** [comment]
@elb0 done in 2ad8d23e01f3e522fbc376a05e4606312b72c900!

**Comment by yuvipanda** [comment]
@elb0 can you tell me when on Friday you're planning on getting students onto the hub? Since this hub is still so new, I would like to be around to monitor things so I can ensure y'all have a good experience.

**Comment by elb0** [comment]
Hi @yuvipanda, sorry I missed this! GitHub notifications still go to my personal account. Everything went super smoothly as far as we could tell. Thank you again for your help!
