### ISSUE TITLE
Larger memory 

### ISSUE THREAD

**Issue by ywis** [utoronto-2i2c/jupyterhub-deploy#33]
Hi there, I see that the default setup is given 2 GB memory. I was wondering if I can ask for a larger memory to run the code. Thanks!

**Comment by ntaback** [comment]
This may be possible depending on the rationale. Is that correct @yuvipanda?  Please send an email to me with your request.

**Comment by yuvipanda** [comment]
Yes, would love to increase RAM if that enables new pedagogical work. Please let us know what you are planning on using it for?

**Comment by ywis** [comment]
Thank you, that would be greatly appreciated! I am just running some code based on my current research work, fitting the spectra+photometry of some galaxies . I am a graduate student at the Department of Astronomy.

**Comment by ntaback** [comment]
@ywis if you are using it for research then I recommend that you use https://www.scinethpc.ca
