### ISSUE TITLE
Installing brms

### ISSUE THREAD

**Issue by RohanAlexander** [utoronto-2i2c/jupyterhub-deploy#34]
Hi thank you very much for this - it's lovely. And sorry if I'm off base adding this issue here.

I am trying to install brms in R Studio (by way of background this draws on R Stan which has already been installed - thank you!).

I can install it:
`install.packages("brms")`

But when I try to call it, I run into an error:
`library("brms")`
```
Error: package or namespace load failed for ‘brms’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/r/igraph/libs/igraph.so':
  libglpk.so.40: cannot open shared object file: No such file or directory

```
I then tried to install igraph, which seemed to work fine.

```
> install.packages("igraph")
Installing package into ‘/opt/r’
(as ‘lib’ is unspecified)
```

So it's clearly there, but still calling the brms library gives that same error, so possibly it's looking in the wrong spot?

```
> library(brms)
Error: package or namespace load failed for ‘brms’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/r/igraph/libs/igraph.so':
  libglpk.so.40: cannot open shared object file: No such file or directory
```

Is this something that could be changed at the admin side please, or should I try to see if I can work something out from my side?

**Comment by ntaback** [comment]
@RohanAlexander  this seems like a job for @yuvipanda .

**Comment by yuvipanda** [comment]
@RohanAlexander thanks for such a clear report! I've installed the required dependencies, and brms as well. LMK if it works.

**Comment by RohanAlexander** [comment]
@yuvipanda OMG it works!!! Thank you! 🙏🙏🙏🙏

Also, thank you to both @yuvipanda & @ntaback for this wonderful resource. It helps such a lot for teaching.
