### ISSUE TITLE
Spot my silly mistake?

### ISSUE THREAD

**Issue by elb0** [utoronto-2i2c/jupyterhub-deploy#36]
Hi folks,

I'm sure I'm just making a dumb mistake, but was wondering if you could help me spot it? This is the repo I want to link to [https://github.com/asidianya/Data-Visualization-](https://github.com/asidianya/Data-Visualization-), and the file I'd like to open in RStudio is [Halloween_ggplot.Rmd](https://github.com/asidianya/Data-Visualization-/blob/main/Halloween_ggplot.Rmd) 

Thanks!
Liza

<img width="1204" alt="Screenshot 2020-11-02 at 10 41 08 AM" src="https://user-images.githubusercontent.com/22538970/97887582-1da8c900-1cf8-11eb-902e-ffa001f2fc01.png">
<img width="1127" alt="Screenshot 2020-11-02 at 10 41 21 AM" src="https://user-images.githubusercontent.com/22538970/97887590-1f728c80-1cf8-11eb-85c8-dc74c4a1ec5f.png">

**Comment by choldgraf** [comment]
your branch needs to be `main` not `master` :-)

**Comment by elb0** [comment]
You absolute legend! Thank you, I'd missed that memo.

**Comment by choldgraf** [comment]
haha - we have been dealing with this issue over at mybinder.org for like 2 weeks now so I know to look for it :-)
