### ISSUE TITLE
Install Mosaic Package

### ISSUE THREAD

**Issue by aslemand** [utoronto-2i2c/jupyterhub-deploy#37]
Hello. This is not an issue but I have been using the mosaic package in my statistics courses and was wondering if this package can be added? Many thanks, Asal

**Comment by ntaback** [comment]
Hi @aslemand .  Glad to hear that you are using it in your course.  @yuvipanda: this is an R package.

**Comment by yuvipanda** [comment]
Glad you find it useful, @aslemand! Installed now :)

**Comment by aslemand** [comment]
@yuvipanda Great. Thank you so much.
