### ISSUE TITLE
Onboard Georgiana to work on UToronto Hub

### ISSUE THREAD

**Issue by yuvipanda** [utoronto-2i2c/jupyterhub-deploy#39]
@GeorgianaElena is now with 2i2c, and will be working with me on supporting hubs - including UToronto hub!

This ticket tracks onboarding her.

- [x] Get utorid
- [x] Add her to Microsoft Teams
- [x] Give her access to the Azure subscription
- [x] Add her to the GitHub organization
- [x] Add her as admin to the JupyterHub
- [x] Test making a change & pushing an image
- [x] Do a deployment to validate the process

**Comment by yuvipanda** [comment]
@GeorgianaElena if you have a working utorid, can you try logging in to jupyter.utoronto.ca?

**Comment by GeorgianaElena** [comment]
@yuvipanda, I was able to login to `jupyter.utoronto.ca`, but no utorid was requested. 
Also, I now have access to Microsoft Teams  :tada:

**Comment by ntaback** [comment]
👋 welcome @GeorgianaElena

**Comment by GeorgianaElena** [comment]
thank you @ntaback and hello :wave:

**Comment by yuvipanda** [comment]
@GeorgianaElena I think you've almost everything here under control. Can you also add yourself as an admin to the JupyterHub so we can close this?

**Comment by yuvipanda** [comment]
See https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/75#issuecomment-764576598
