### ISSUE TITLE
Can students with guest UTORIDs access the JupyterHub?

### ISSUE THREAD

**Issue by elb0** [utoronto-2i2c/jupyterhub-deploy#40]
Hi folks! For a small outreach program to high school student next year, we were hoping to use JupyterHub for a one-day event. The students will be set up with guest UTORIDs that will give them access to Quercus. Will this be sufficient for access to JupyterHub also?

**Comment by yuvipanda** [comment]
Hello @elb0! I think they should be, since we don't differentiate on type of utorid. However, if you can get access to one and test it out, that would be most helpful!

**Comment by elb0** [comment]
Thanks, I'll see if I can!

**Comment by colliand** [comment]
Hi Liza! Another possibility is to use the Jupyter resource offered by Callysto. That service is aimed at allowing universities like the University of Toronto to carry out data/computing outreach leveraging Jupyter. Here are two related links:
+ [https://www.callysto.ca/](https://www.callysto.ca/)
+ [https://hub.callysto.ca/](https://hub.callysto.ca/)
Callysto sometimes has calls for proposals with funding to support outreach activities in Canada.
