### ISSUE TITLE
Loading rJava

### ISSUE THREAD

**Issue by elb0** [utoronto-2i2c/jupyterhub-deploy#65]
Hi @yuvipanda,

I have the same issue in JupyterHub as expressed here: https://github.com/rstudio/rstudio/issues/2254.
It is low priority, but if you get a chance, would you take look if it is easy enough to solve?

Use case: creating a function, that uses `staplr::split_pdf()`, to help students to split their homework into separate PDF for submission to Crowdmark. 

It's probably working if you can run the below in R without it throwing an error:
```
install.packages("staplr")
library(staplr)
```

If it is possible, it would be awesome to have `staplr` added to `install.R`.

Thanks!
Liza

**Comment by GeorgianaElena** [comment]
Hey @elb0 :wave:

`staplr` and `rJava` should now be available on the staging hub (https://staging.utoronto.2i2c.cloud/), soon to be added to the production one too <3

When loading these libraries, no errors occurred, but It would be super nice if you could confirm that everything works at it should :heart: Thank you!
