### ISSUE TITLE
Loading copula package

### ISSUE THREAD

**Issue by spesenti** [utoronto-2i2c/jupyterhub-deploy#89]
I created nbgitpuller to my repository where I use the R package copula. 

On JupyterHub, the copula package installs correctly, but it cannot load it and R provides the error 

> require(copula)
Loading required package: copula
Error: package or namespace load failed for ‘copula’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/r/gsl/libs/gsl.so':
  libgsl.so.23: cannot open shared object file: No such file or directory

That's the link: 
http://jupyter.utoronto.ca/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fspesenti%2FSTA4528&urlpath=rstudio%2F&branch=main

**Comment by GeorgianaElena** [comment]
Hey @spesenti :wave:

The `copula` package should now be available if you restart your JupyterHub server.
Please let me know if it works.

**Comment by spesenti** [comment]
Works beautifully! Many thanks @GeorgianaElena.
