### ISSUE TITLE
Access to Grafana

### ISSUE THREAD

**Issue by VijayMaraviya** [utoronto-2i2c/jupyterhub-deploy#91]
@yuvipanda , @GeorgianaElena It seems that Microsoft Team is still not working for Yuvi. So, I trying to connect here. 

Could you please provide me the access to Grafana? We are working on the reporting and optimization project at Jupyter Operations group and would love your participation.

**Comment by yuvipanda** [comment]
Ah, thanks for opening this, @VijayMaraviya! I'll get this done once the weekday starts.

**Comment by yuvipanda** [comment]
I've sent you an invite to this organization (utoronto-2i2c) on GitHub. Once you accept it, can you look at grafana.utoronto.2i2c.cloud and see if you can log-in?

**Comment by VijayMaraviya** [comment]
@yuvipanda Thank you so much😊 I have the access now.

**Comment by yuvipanda** [comment]
Yay! Please let me know if others need access too.

**Comment by VijayMaraviya** [comment]
Sure. I will ask them to comment here. For Github ID..👍

**Comment by Akshat2395** [comment]
Hi @yuvipanda, I would like to have access to Grafana as well. Thanks!

**Comment by yuvipanda** [comment]
@Akshat2395 done.

**Comment by RuyiPan** [comment]
Hi @yuvipanda , I would like to have access to Grafana. Thanks in advance!

**Comment by yuvipanda** [comment]
Done, @RuyiPan
