### ISSUE TITLE
unable to launch a notebook from JupyterLab

### ISSUE THREAD

**Issue by ntaback** [utoronto-2i2c/jupyterhub-deploy#95]
@yuvipanda Everything else seems to work from JupyterLab except Python/R notebooks.

<img width="904" alt="Screen Shot 2021-06-02 at 5 32 01 PM" src="https://user-images.githubusercontent.com/11906681/120555136-9c69ff80-c3c8-11eb-996f-bf7314dad1da.png">

**Comment by yuvipanda** [comment]
@ntaback can you tell me what browser this is? I can launch this on Firefox, and I don't recognize the browser in use.

**Comment by choldgraf** [comment]
closing this one as I don't think we have enough information to reproduce the issue
